# This is the name of the workflow, visible on GitHub UI.
name: make

# Here we tell GitHub to run the workflow when a commit
# is pushed or a Pull Request is opened.
on: [push, pull_request]

# This is the list of jobs that will be run concurrently.
# Since we use a build matrix, the actual number of jobs
# started depends on how many configurations the matrix
# will produce.
jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: 'src'
        exclude: './third_party'
        extensions: 'h,cpp,ino'
        clangFormatVersion: 9

  cpp-unittest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Compile
      run: |
          cd test/tonella/
          mkdir build
          cd build
          cmake ..
          make googletest
          make runTests
          make runTestsCov
    - name: Run
      run: |
          cd test/tonella/build
          ./runTests
    - name: Code Coverage
      run: |
          sudo apt install lcov
          cd test/tonella/build
          ./runTestsCov
          lcov -d CMakeFiles/runTestsCov.dir -c -o ex_test.info
          lcov -r ex_test.info /usr/include/\* $PWD/include/gmock/\* $PWD/include/gtest/\* \*/test/tonella/\* -o ex_test_filtered.info
          genhtml ex_test_filtered.info -o res
    - uses: actions/upload-artifact@v1
      with:
        name: codeCoverageReport
        path: test/tonella/build/res

  cpp-doc:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Doxygen
      run: |
          sudo apt install doxygen
    - name: Run Doxygen
      run: |
          cd doc
          doxygen Doxyfile

  python-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3

  python-doc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Python Docstring Checker
      run: |
          pip3 install pydocstyle --user
          ~/.local/bin/pydocstyle src
      
