name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO
      run: |
        cd src/tonella
        pio run
    - name: Copy binaries
      run: |
        mkdir build
        cp src/tonella/.pio/build/nanoatmega328/firmware.* build/
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
